"""
FaceMatch Pro - PDF Report Generator
Requires: reportlab, Pillow
"""

import os
import datetime
from typing import Dict, Any, Optional
from utils import make_report_id

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm, cm
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                     Table, TableStyle, Image as RLImage,
                                     HRFlowable, KeepTogether)
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

try:
    from PIL import Image as PILImage
    PIL_AVAILABLE = True
except ImportError:
    PIL_AVAILABLE = False


# ─── Colour palette ────────────────────────────────────────────────────────────
BG        = colors.HexColor("#0F172A")
CARD      = colors.HexColor("#1E293B")
ACCENT    = colors.HexColor("#8B5CF6")
ACCENT2   = colors.HexColor("#6366F1")
SUCCESS   = colors.HexColor("#10B981")
WARNING   = colors.HexColor("#F59E0B")
DANGER    = colors.HexColor("#EF4444")
WHITE     = colors.white
LIGHT     = colors.HexColor("#CBD5E1")


def generate_report(result: Dict[str, Any],
                    image1_path: str,
                    image2_path: str,
                    output_dir: str = "reports") -> str:
    """
    Generate a professional PDF report.
    Returns the full path to the saved PDF file.
    """
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError("reportlab is not installed. Run: pip install reportlab")

    os.makedirs(output_dir, exist_ok=True)
    report_id = make_report_id()
    filename  = f"FaceMatchPro_{report_id}.pdf"
    filepath  = os.path.join(output_dir, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=20*mm, rightMargin=20*mm,
        topMargin=15*mm, bottomMargin=15*mm,
        title=f"FaceMatch Pro Report – {report_id}",
    )

    story = []
    styles = _build_styles()
    W, H = A4
    content_w = W - 40*mm

    # ── Header ─────────────────────────────────────────────────────────────────
    story.append(_header_table(report_id, styles, content_w))
    story.append(Spacer(1, 8*mm))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
    story.append(Spacer(1, 6*mm))

    # ── Images section ─────────────────────────────────────────────────────────
    story.append(Paragraph("FACE IMAGES ANALYZED", styles["section_title"]))
    story.append(Spacer(1, 4*mm))
    story.append(_images_table(image1_path, image2_path, result, styles, content_w))
    story.append(Spacer(1, 8*mm))

    # ── Score banner ───────────────────────────────────────────────────────────
    story.append(_score_banner(result, styles, content_w))
    story.append(Spacer(1, 8*mm))

    # ── Detail table ───────────────────────────────────────────────────────────
    story.append(Paragraph("ANALYSIS BREAKDOWN", styles["section_title"]))
    story.append(Spacer(1, 4*mm))
    story.append(_detail_table(result, styles, content_w))
    story.append(Spacer(1, 8*mm))

    # ── System info ────────────────────────────────────────────────────────────
    story.append(Paragraph("SYSTEM INFORMATION", styles["section_title"]))
    story.append(Spacer(1, 4*mm))
    story.append(_system_table(result, styles, content_w))
    story.append(Spacer(1, 12*mm))

    # ── Footer ─────────────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
    story.append(Spacer(1, 4*mm))
    story.append(Paragraph(
        f"Generated by FaceMatch Pro  •  {datetime.datetime.now().strftime('%B %d, %Y %H:%M:%S')}  •  Report ID: {report_id}",
        styles["footer"],
    ))

    doc.build(story)
    return filepath


# ─── Private helpers ────────────────────────────────────────────────────────────

def _build_styles():
    base = getSampleStyleSheet()
    s = {}

    def ps(name, **kw):
        s[name] = ParagraphStyle(name, **kw)

    ps("app_title",   fontSize=26, textColor=WHITE,     alignment=TA_LEFT,
       fontName="Helvetica-Bold", spaceAfter=2)
    ps("app_sub",     fontSize=10, textColor=LIGHT,     alignment=TA_LEFT,
       fontName="Helvetica")
    ps("report_id",   fontSize=9,  textColor=ACCENT,    alignment=TA_RIGHT,
       fontName="Helvetica-Bold")
    ps("report_date", fontSize=9,  textColor=LIGHT,     alignment=TA_RIGHT,
       fontName="Helvetica")
    ps("section_title", fontSize=11, textColor=ACCENT,  fontName="Helvetica-Bold",
       spaceAfter=2, spaceBefore=2)
    ps("cell_label",  fontSize=9,  textColor=LIGHT,     fontName="Helvetica")
    ps("cell_value",  fontSize=10, textColor=WHITE,     fontName="Helvetica-Bold")
    ps("score_big",   fontSize=44, textColor=WHITE,     alignment=TA_CENTER,
       fontName="Helvetica-Bold")
    ps("score_label", fontSize=12, textColor=LIGHT,     alignment=TA_CENTER,
       fontName="Helvetica")
    ps("match_label", fontSize=18, textColor=WHITE,     alignment=TA_CENTER,
       fontName="Helvetica-Bold")
    ps("footer",      fontSize=8,  textColor=LIGHT,     alignment=TA_CENTER,
       fontName="Helvetica")
    ps("img_caption", fontSize=8,  textColor=LIGHT,     alignment=TA_CENTER,
       fontName="Helvetica")
    return s


def _card_table_style(rows: int):
    return TableStyle([
        ("BACKGROUND",  (0,0), (-1,-1), CARD),
        ("TEXTCOLOR",   (0,0), (-1,-1), WHITE),
        ("GRID",        (0,0), (-1,-1), 0.3, colors.HexColor("#334155")),
        ("ROUNDEDCORNERS", [4]),
        ("LEFTPADDING",  (0,0), (-1,-1), 10),
        ("RIGHTPADDING", (0,0), (-1,-1), 10),
        ("TOPPADDING",   (0,0), (-1,-1), 7),
        ("BOTTOMPADDING",(0,0), (-1,-1), 7),
    ])


def _header_table(report_id, styles, width):
    now = datetime.datetime.now()
    left = [
        Paragraph("FaceMatch Pro", styles["app_title"]),
        Paragraph("AI Face Verification &amp; Similarity System", styles["app_sub"]),
    ]
    right = [
        Paragraph(f"Report ID: {report_id}", styles["report_id"]),
        Paragraph(now.strftime("%B %d, %Y  %H:%M:%S"), styles["report_date"]),
    ]
    t = Table([[left, right]], colWidths=[width*0.55, width*0.45])
    t.setStyle(TableStyle([
        ("VALIGN",      (0,0), (-1,-1), "TOP"),
        ("BACKGROUND",  (0,0), (-1,-1), BG),
        ("LEFTPADDING", (0,0), (-1,-1), 0),
        ("RIGHTPADDING",(0,0), (-1,-1), 0),
    ]))
    return t


def _images_table(path1, path2, result, styles, width):
    def make_cell(img_path, label, dims, quality):
        cell = []
        # Try to embed image thumbnail
        if PIL_AVAILABLE and img_path and os.path.exists(img_path):
            try:
                img = PILImage.open(img_path).convert("RGB")
                img.thumbnail((120, 120))
                tmp = img_path + "_thumb.jpg"
                img.save(tmp, "JPEG")
                cell.append(RLImage(tmp, width=90, height=90))
            except Exception:
                cell.append(Paragraph("[Image]", styles["img_caption"]))
        else:
            cell.append(Paragraph("[Image]", styles["img_caption"]))
        cell.append(Spacer(1, 2*mm))
        cell.append(Paragraph(label, styles["cell_label"]))
        cell.append(Paragraph(os.path.basename(img_path) if img_path else "—", styles["cell_value"]))
        cell.append(Paragraph(f"Dimensions: {dims[0]}×{dims[1]} px", styles["cell_label"]))
        cell.append(Paragraph(f"Quality Score: {quality}%", styles["cell_label"]))
        return cell

    d1 = result.get("dims_1", (0,0))
    d2 = result.get("dims_2", (0,0))
    q1 = result.get("face_quality_1", 0)
    q2 = result.get("face_quality_2", 0)

    c1 = make_cell(path1, "Image 1", d1, q1)
    c2 = make_cell(path2, "Image 2", d2, q2)

    t = Table([[c1, c2]], colWidths=[width/2-2*mm, width/2-2*mm])
    t.setStyle(_card_table_style(1))
    return t


def _score_banner(result, styles, width):
    score  = result.get("similarity_score", 0)
    status = result.get("match_status", "No Match")
    label  = result.get("match_label", "No Match")
    colour = SUCCESS if status == "Match" else DANGER

    sign   = "✓" if status == "Match" else "✗"

    inner = [
        [Paragraph(f"{score:.2f}%", styles["score_big"])],
        [Paragraph("SIMILARITY SCORE", styles["score_label"])],
        [Spacer(1, 4*mm)],
        [Paragraph(f"{sign}  {label}", styles["match_label"])],
    ]
    inner_t = Table(inner, colWidths=[width])
    inner_t.setStyle(TableStyle([
        ("BACKGROUND",   (0,0), (-1,-1), colours_blend(colour)),
        ("ALIGN",        (0,0), (-1,-1), "CENTER"),
        ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
        ("LEFTPADDING",  (0,0), (-1,-1), 10),
        ("RIGHTPADDING", (0,0), (-1,-1), 10),
        ("TOPPADDING",   (0,0), (-1,-1), 10),
        ("BOTTOMPADDING",(0,0), (-1,-1), 10),
        ("ROUNDEDCORNERS", [6]),
    ]))
    return inner_t


def colours_blend(c):
    """Darken a colour for background use."""
    r = int(c.red * 255 * 0.25)
    g = int(c.green * 255 * 0.25)
    b = int(c.blue * 255 * 0.25)
    return colors.Color(r/255, g/255, b/255)


def _detail_table(result, styles, width):
    rows = [
        ["Metric", "Score"],
        ["Histogram Similarity", f"{result.get('histogram_score',0):.2f}%"],
        ["Structural Similarity (SSIM)", f"{result.get('ssim_score',0):.2f}%"],
        ["Feature Vector Similarity", f"{result.get('feature_score',0):.2f}%"],
        ["Final Weighted Score", f"{result.get('similarity_score',0):.2f}%"],
        ["Confidence Level", f"{result.get('confidence',0):.1f}%"],
        ["Face Quality — Image 1", f"{result.get('face_quality_1',0):.2f}%"],
        ["Face Quality — Image 2", f"{result.get('face_quality_2',0):.2f}%"],
        ["Verification Result", result.get("match_status","—")],
        ["Classification", result.get("match_label","—")],
    ]
    col_w = [width*0.6, width*0.4]
    t = Table(rows, colWidths=col_w)
    style = _card_table_style(len(rows))
    style.add("BACKGROUND", (0,0), (-1,0), ACCENT2)
    style.add("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold")
    style.add("ROWBACKGROUNDS", (0,1), (-1,-1), [CARD, colors.HexColor("#253044")])
    t.setStyle(style)
    return t


def _system_table(result, styles, width):
    rows = [
        ["Property", "Value"],
        ["Processing Time",  f"{result.get('processing_time',0)*1000:.1f} ms"],
        ["Image 1 Dimensions", f"{result.get('dims_1',(0,0))[0]} × {result.get('dims_1',(0,0))[1]} px"],
        ["Image 2 Dimensions", f"{result.get('dims_2',(0,0))[0]} × {result.get('dims_2',(0,0))[1]} px"],
        ["Analysis Engine", "OpenCV + NumPy (no heavy AI framework)"],
        ["Report Generated", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
    ]
    t = Table(rows, colWidths=[width*0.45, width*0.55])
    style = _card_table_style(len(rows))
    style.add("BACKGROUND", (0,0), (-1,0), ACCENT2)
    style.add("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold")
    t.setStyle(style)
    return t
